import { BackSide, CircleGeometry, ConeGeometry, CylinderGeometry, Group, Mesh, MeshBasicMaterial, MeshStandardMaterial, SphereGeometry, TorusGeometry, type Object3D, type Scene } from 'three';
import type { PelletSnapshot, TargetSnapshot } from './GameClient';

export default class CombatObjects {
  private root=new Group(); private pellets=new Map<string,Group>(); private pool:Group[]=[]; private targets=new Map<string,Object3D>();
  private pelletGeometry=new SphereGeometry(.28,8,6); private pelletMaterial=new MeshStandardMaterial({color:'#ff74ad',emissive:'#8c174d',emissiveIntensity:.7});
  constructor(scene:Scene){scene.add(this.root)}
  sync(pellets:PelletSnapshot[],targets:TargetSnapshot[]):void{const live=new Set(pellets.map(p=>p.id));for(const[id,group]of this.pellets)if(!live.has(id)){group.visible=false;this.pellets.delete(id);this.pool.push(group)}for(const pellet of pellets){let group=this.pellets.get(pellet.id);if(!group){group=this.pool.pop()??this.createPellet();group.visible=true;this.pellets.set(pellet.id,group)}group.position.set(pellet.x,pellet.y,pellet.z)}for(const target of targets){let object=this.targets.get(target.id);if(!object){object=target.kind==='balloon'?this.createBalloon():this.createBullseye();this.targets.set(target.id,object);this.root.add(object)}object.position.set(target.x,target.y,target.z);object.visible=target.active;if(!target.active)object.scale.setScalar(.15);else object.scale.lerp({x:1,y:1,z:1} as any,.3)}}
  update(delta:number,reducedMotion=false):void{if(reducedMotion)return;const time=performance.now()*.001;this.targets.forEach((target,id)=>{if(target.visible){target.rotation.y+=delta*(id.includes('balloon')?.7:.25);if(id.includes('balloon'))target.position.y+=Math.sin(time+target.position.x)*.0025}})}
  destroy():void{this.root.removeFromParent();this.root.traverse((object:any)=>{object.geometry?.dispose?.();const material=object.material;if(Array.isArray(material))material.forEach((item:any)=>item.dispose());else material?.dispose?.()});this.pelletGeometry.dispose();this.pelletMaterial.dispose();this.pellets.clear();this.targets.clear();this.pool.length=0}
  private createPellet():Group{const group=new Group(),pellet=new Mesh(this.pelletGeometry,this.pelletMaterial),trail=new Mesh(new ConeGeometry(.13,1.2,6),new MeshBasicMaterial({color:'#ffd1e2',transparent:true,opacity:.45}));trail.rotation.x=-Math.PI/2;trail.position.z=.65;group.add(pellet,trail);this.root.add(group);return group}
  private createBalloon():Group{const group=new Group(),jelly=new Mesh(new SphereGeometry(1.35,14,10),new MeshStandardMaterial({color:'#f06d9e',roughness:.42,transparent:true,opacity:.92})),outline=new Mesh(jelly.geometry.clone(),new MeshBasicMaterial({color:'#2b1822',side:BackSide}));outline.scale.setScalar(1.07);jelly.add(outline);jelly.scale.y=1.18;const knot=new Mesh(new ConeGeometry(.22,.45,7),new MeshStandardMaterial({color:'#f06d9e'}));knot.position.y=-1.5;knot.rotation.z=Math.PI;const basket=new Mesh(new CylinderGeometry(.3,.4,.45,8),new MeshStandardMaterial({color:'#8a5037'}));basket.position.y=-2.25;group.add(jelly,knot,basket);return group}
  private createBullseye():Group{const group=new Group(),back=new Mesh(new CylinderGeometry(1.9,1.9,.25,24),new MeshStandardMaterial({color:'#fff0b6',roughness:.9}));back.rotation.x=Math.PI/2;group.add(back);for(const[r,color,z]of[[1.35,'#dd4e43',-.15],[.8,'#fff0b6',-.19],[.34,'#34202a',-.23]]as const){const disc=new Mesh(new CircleGeometry(r,24),new MeshBasicMaterial({color}));disc.position.z=z;group.add(disc)}const rim=new Mesh(new TorusGeometry(1.9,.16,8,24),new MeshStandardMaterial({color:'#34202a'}));group.add(rim);return group}
}
