import { AdditiveBlending, BufferGeometry, Color, Float32BufferAttribute, Group, LineBasicMaterial, LineSegments, Vector3, type PerspectiveCamera, type Scene } from 'three';
import type { CombatEvent, PlayerSnapshot } from './GameClient';

export default class ComicEffects {
  private root=new Group(); private speedLines:LineSegments; private notices=new Set<HTMLElement>();
  constructor(scene:Scene,private camera:PerspectiveCamera){const positions:number[]=[];for(let i=0;i<28;i++){const angle=i/28*Math.PI*2,r=1.8+(i%4)*.14;positions.push(Math.cos(angle)*r,Math.sin(angle)*r,-3,Math.cos(angle)*r*1.45,Math.sin(angle)*r*1.45,-5)}const geometry=new BufferGeometry();geometry.setAttribute('position',new Float32BufferAttribute(positions,3));this.speedLines=new LineSegments(geometry,new LineBasicMaterial({color:'#fff2b8',transparent:true,opacity:0,blending:AdditiveBlending,depthTest:false}));this.speedLines.frustumCulled=false;camera.add(this.speedLines);scene.add(this.root)}
  update(local:PlayerSnapshot|undefined,reducedMotion:boolean):void{const speed=local?.speed??0;const target=!reducedMotion&&speed>19?Math.min(.24,(speed-19)*.025):0;(this.speedLines.material as LineBasicMaterial).opacity+=(target-(this.speedLines.material as LineBasicMaterial).opacity)*.12;this.speedLines.rotation.z+=reducedMotion?0:.002*speed}
  event(event:CombatEvent,worldPosition:Vector3|undefined,reducedMotion:boolean):void{const words:Record<string,string>={shot:'PFT!', 'plane-hit':event.kind==='collision'?'FWOMP!':'SPLAT!', 'target-hit':'POP!',knockout:'PUTT-PUTT…',crash:'PANCAKE!',respawn:'KABOOM!'};const word=words[event.type];if(!word)return;const element=document.createElement('strong');element.className='comic-burst';element.textContent=word;element.style.setProperty('--burst-color',event.type==='crash'?'#f0bd3d':'#ff6f61');if(worldPosition){const projected=worldPosition.clone().project(this.camera);element.style.left=`${(projected.x*.5+.5)*100}%`;element.style.top=`${(-projected.y*.5+.5)*100}%`}else{element.style.left='50%';element.style.top='42%'}if(reducedMotion)element.classList.add('is-reduced');document.querySelector('[data-effects-layer]')?.append(element);this.notices.add(element);window.setTimeout(()=>{element.remove();this.notices.delete(element)},reducedMotion?350:850)}
  destroy():void{this.notices.forEach(item=>item.remove());this.notices.clear();this.speedLines.removeFromParent();this.speedLines.geometry.dispose();(this.speedLines.material as LineBasicMaterial).dispose();this.root.removeFromParent()}
}
