import { CanvasTexture, Group, MathUtils, Quaternion, Sprite, SpriteMaterial, SRGBColorSpace, Vector3 } from 'three';
import { GAME_CONFIG } from './config';
import { getPlaneDefinition } from './planes';
import type { PlayerSnapshot } from './GameClient';
export type JellyEvent='hit'|'collision'|'knockout'|'crash'|'respawn';
export default class Player {
  readonly group=new Group();readonly isLocal:boolean;private visual:Group;private target=new Vector3();private targetQ=new Quaternion();private label:Sprite;private healthBar:Sprite;private name:string;private health=100;private lastDamageAt=-100;private status='flying';private speed=13;private wobble=0;private squash=0;private clock=0;
  constructor(s:PlayerSnapshot){this.isLocal=s.isLocal;this.visual=getPlaneDefinition(s.planeDefinitionId).createVisual(s.color);this.label=label(s.displayName,s.color,s.isLocal);this.healthBar=healthBar(s.health);this.name=s.displayName;this.health=s.health;this.lastDamageAt=s.lastDamageAt;this.status=s.flightStatus;this.speed=s.speed;this.group.add(this.visual,this.label,this.healthBar);this.group.position.set(s.x,s.y,s.z);this.target.copy(this.group.position);this.group.quaternion.set(s.quaternionX,s.quaternionY,s.quaternionZ,s.quaternionW);this.targetQ.copy(this.group.quaternion)}
  applySnapshot(s:PlayerSnapshot):void{this.target.set(s.x,s.y,s.z);this.targetQ.set(s.quaternionX,s.quaternionY,s.quaternionZ,s.quaternionW).normalize();this.lastDamageAt=s.lastDamageAt;this.status=s.flightStatus;this.speed=s.speed;if(s.health!==this.health){this.health=s.health;drawHealth(this.healthBar,s.health)}if(s.displayName!==this.name){this.group.remove(this.label);dispose(this.label);this.label=label(s.displayName,s.color,s.isLocal);this.group.add(this.label);this.name=s.displayName}if(s.altitudeFrozen)this.wobble=Math.max(this.wobble,.18)}
  react(type:JellyEvent):void{if(type==='hit')this.wobble=Math.max(this.wobble,.42);if(type==='collision')this.wobble=Math.max(this.wobble,.7);if(type==='knockout')this.wobble=1;if(type==='crash')this.squash=1;if(type==='respawn'){this.squash=0;this.wobble=.5}}
  setHealthContext(targeted:boolean,serverTime:number):void{this.healthBar.visible=!this.isLocal&&(targeted||(this.health<100&&serverTime-this.lastDamageAt<3))}
  update(dt:number,reduced=false):void{this.clock+=dt;const interpolation=1-Math.exp(-GAME_CONFIG.network.interpolation*dt);this.group.position.lerp(this.target,interpolation);this.group.quaternion.slerp(this.targetQ,interpolation);const propeller=this.visual.getObjectByName('propeller');if(propeller)propeller.rotation.z+=dt*(this.status==='disabled'?3:12+this.speed*.55);const smoke=this.visual.getObjectByName('disabled-smoke');if(smoke){smoke.visible=this.status==='disabled';smoke.rotation.y+=dt*.7;smoke.position.y=Math.sin(this.clock*3)*.08}const wings=this.visual.getObjectByName('jelly-wings'),body=this.visual.getObjectByName('jelly-body'),motion=reduced?.25:1,flutter=(this.status==='disabled'?Math.sin(this.clock*11)*.16:Math.sin(this.clock*7)*.025)*motion;if(wings){wings.rotation.z=flutter+Math.sin(this.clock*18)*this.wobble*.08*motion;wings.scale.y=1+Math.sin(this.clock*15)*this.wobble*.09*motion}if(body){body.scale.x=1+Math.sin(this.clock*20)*this.wobble*.09*motion;body.scale.y=1-Math.sin(this.clock*20)*this.wobble*.05*motion}const pancake=this.status==='pancaked'?1:this.squash;this.visual.scale.y=MathUtils.damp(this.visual.scale.y,1-pancake*.72,12,dt);this.visual.scale.x=MathUtils.damp(this.visual.scale.x,1+pancake*.38,12,dt);this.visual.scale.z=MathUtils.damp(this.visual.scale.z,1+pancake*.3,12,dt);this.wobble=Math.max(0,this.wobble-dt*1.7);this.squash=Math.max(0,this.squash-dt*.5)}
  destroy():void{this.group.removeFromParent();this.visual.traverse((o:any)=>{o.geometry?.dispose?.();const m=o.material;if(Array.isArray(m))m.forEach((item:any)=>item.dispose());else m?.dispose?.()});dispose(this.label);dispose(this.healthBar)}
}
function label(name:string,color:string,local:boolean):Sprite{const c=document.createElement('canvas');c.width=512;c.height=128;const x=c.getContext('2d')!;x.fillStyle='rgba(38,22,27,.82)';x.roundRect(8,8,496,112,22);x.fill();x.strokeStyle=local?'#fff4c7':color;x.lineWidth=7;x.stroke();x.fillStyle='#fff8df';x.font='900 42px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(name,256,64,450);const t=new CanvasTexture(c);t.colorSpace=SRGBColorSpace;const s=new Sprite(new SpriteMaterial({map:t,transparent:true,depthTest:false}));s.position.y=2.2;s.scale.set(2.5,.62,1);return s}
function healthBar(health:number):Sprite{const c=document.createElement('canvas');c.width=256;c.height=32;const t=new CanvasTexture(c);t.colorSpace=SRGBColorSpace;const s=new Sprite(new SpriteMaterial({map:t,transparent:true,depthTest:false}));s.position.y=2.95;s.scale.set(2.8,.35,1);s.visible=false;drawHealth(s,health);return s}
function drawHealth(s:Sprite,health:number):void{const t=(s.material as SpriteMaterial).map!,c=t.image as HTMLCanvasElement,x=c.getContext('2d')!;x.clearRect(0,0,c.width,c.height);x.fillStyle='#291820';x.fillRect(0,0,256,32);x.fillStyle=health>50?'#73c96d':health>25?'#f2c14f':'#ed5b4e';x.fillRect(4,4,248*MathUtils.clamp(health/100,0,1),24);x.strokeStyle='#fff2c2';x.lineWidth=3;x.strokeRect(1.5,1.5,253,29);t.needsUpdate=true}
function dispose(s:Sprite):void{const m=s.material as SpriteMaterial;m.map?.dispose();m.dispose()}
